language: java

script:
- ./gradlew checkstyleMain checkstyleTest && ./gradlew test && ./gradlew seleniumXvfb 

deploy:
    provider: heroku
    api_key: 600638ea-78da-42d7-81f1-2cc4d6f8e2e1
    app: tttweb
    on: table
    skip_cleanup: true
    strategy: git

notifications:
  email:
    recipients:
      - bjornb13@ru.is
    on_success: always # default: always
    on_failure: always # default: always