language: java

script:
- ./sbin/tests

deploy:
    provider: heroku
    api_key: 600638ea-78da-42d7-81f1-2cc4d6f8e2e1
    app: tttwebstage
    on: table
    skip_cleanup: true
    strategy: git
after_deploy:
  - ./gradlew seleniumXvfb


notifications:
  email:
    recipients:
      - bjornb13@ru.is
    on_success: always # default: always
    on_failure: always # default: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"