/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bjorni' at '10/23/14 2:57 PM' with Gradle 2.1
 *
 * @author bjorni, @date 10/23/14 2:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
