#!/bin/bash

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "---------------"
  echo "Generating docs"
  echo "---------------"
  
  ./gradlew javadoc cobertura -x selenium -x seleniumXvfb
  
  echo -e "Publishing docs...\n"

  cp -R build/docs/javadoc $HOME/javadoc-latest
  cp -R build/reports/cobertura $HOME/cobertura-latest
  
  cd $HOME
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "travis-ci"
  git clone --quiet --branch=gh-pages https://670645a4eadfc2ffa826700033c2802de9c754c9@github.com/thotulidid/TicTacToeGame gh-pages > /dev/null

  cd gh-pages
  git rm -rf ./javadoc
  git rm -rf ./cobertura
  cp -Rf $HOME/javadoc-latest ./javadoc
  cp -Rf $HOME/cobertura-latest ./cobertura
  git add -f .
  git commit -m "Latest docs on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
  git push -fq origin gh-pages > /dev/null

  echo -e "Published docs to gh-pages.\n"
  
fi

