#!/bin/bash

if ! ./gradlew checkstyleMain checkstyleTest; then
  echo "Style check failed"
  exit 1
fi

if ! ./gradlew test; then
  echo "Unit tests failed"
  exit 1
fi

if ! ./gradlew seleniumXvfb; then
  echo "Functional tests failed"
  exit 1
fi

